const encryptedConfig = "eyJhcGlLZXkiOiAiQUl6YVN5QUJjNWVZM3FxdkwxU3pJcEtIOC1nV2FFY3JSZHg2cFpRIiwgImF1dGhEb21haW4iOiAicmljb3dhLTYzOTQ1LmZpcmViYXNlYXBwLmNvbSIsICJwcm9qZWN0SWQiOiAicmljb3dhLTYzOTQ1IiwgInN0b3JhZ2VCdWNrZXQiOiAicmljb3dhLTYzOTQ1LmFwcHNwb3QuY29tIiwgIm1lc3NhZ2luZ1NlbmRlcklkIjogIjUyOTY1MTU3OTgxMCIsICJhcHBJZCI6ICIxOjUyOTY1MTU3OTgxMDp3ZWI6MWE4Njg0YmE4MDE5NzRlNzgwZDBmYiJ9";
const firebaseConfig = JSON.parse(atob(encryptedConfig));
firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();
